services:
  under-the-tree-database:
    container_name: under-the-tree-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ${DOCKER_USERNAME}/under-the-tree-database
    environment:
      - MARIADB_DATABASE=under_the_tree
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"