spring:
    datasource:
        hikari:
            maximum-pool-size: 4
        url: jdbc:mariadb://localhost:3306/under_the_tree
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
spring.jpa:
    hibernate:
        dialect: org.hibernate.dialect.MariaDB
        ddl-auto: update
    show-sql: true